### ISSUE TITLE
Unexpected NaN Values in sequence_index After Updating to SDV 1.10.0

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1808]
* SDV version: 1.10.0
* Python version: 3.8.10
* Operating System: Linux

After updating to SDV version 1.10.0, I've noticed an issue: my synthetic data's sequence_index is now filled with a surprising amount of NaN values, a problem I didn't face with version 1.9.0. notice that my sequence_index column has no Nan values in the original dataset
![Screenshot from 2024-02-21 10-21-14](https://github.com/sdv-dev/SDV/assets/17408097/ea0e6ebc-0e7c-440b-857f-e086f583b1e4)
this is from version 1.10.0 , a lot of Nan values even though there is no nan values in the real dataset ( the repeating in the first date column is intentional, so please ignore this )

![Screenshot from 2024-02-21 10-26-53](https://github.com/sdv-dev/SDV/assets/17408097/fa0cfdd1-d4c3-4aab-864d-4a2c8643eb8f)
this is from version 10.9.0 , there is a repeating values but no Nan as in the real dataset

**Comment by npatki** [comment]
Hi @Ng-ms thanks for providing the details. Unfortunately, we have been unable to replicate the case where the synthetic data is producing NaN values. Could you provide the following information?

1. Please share **the metadata for this table**. It will contain information about the column names, and which columns are the sequence key and sequence index. 
2. As a sanity check, could you run the code below on your **real data**, and let us know the output?

```python
import pandas as pd

SEQUENCE_INDEX = 'column_name' # TODO replace 'column_name' with the name of your sequence index
DATA = data # TODO replace with the variable for your real data

print('Real data contains null values?:', pd.isnull(DATA[SEQUENCE_INDEX]).any())
print('Data type:', DATA[SEQUENCE_INDEX].dtype)
```

**Comment by Ng-ms** [comment]
`Real data contains null values?: False
`
![Screenshot from 2024-02-21 17-27-25](https://github.com/sdv-dev/SDV/assets/17408097/0a8259bf-8e60-45c9-b313-a6beeef8c37b)
and this is part of my metadata
{
    "sequence_key": "ID_P",
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1",
    "columns": {
        "ID_P: {
            "sdtype": "id"
        },
        "Date_Pr": {
            "sdtype": "datetime"
        },
        "Date_register": {
            "sdtype": "datetime"
        },
        "pre_dia": {
            "sdtype": "categorical"
        },
        "calori": {
            "sdtype": "categorical"
  },
    "sequence_index": "Date_register"
}

**Comment by npatki** [comment]
Hi @Ng-ms, thanks for sharing the metadata. I can confirm that from this info, there seems to be no issues in the metadata specification or data representation. However, I am still unable to replicate the issue -- as when I create data that matches, it does not produce any NaN values.

I can reach out to our engineering team to figure out what may be the cause. In the meantime, is there any more information you can provide to help us replicate this issue? (I'm not sure if you are able to share data and metadata). The sooner we can replicate, the sooner we can have a fix. Thanks.

**Comment by ImmortalSector** [comment]
I am encountering the same problem for the exact same case, however my column is becoming totally empty... Until further notice, I will keep using the 1.9 version :(

**Comment by npatki** [comment]
Hi @ImmortalSector sorry to hear that. This one is tricky because we have been unable to replicate it on our end (yet!). Would you be able to provide more information that could help us reproduce the bug? Perhaps if you're able to share data and metadata that causes this behavior?

**Comment by npatki** [comment]
Hi @XiaPoppy do you mean to say that [Kaggle dataset](https://www.kaggle.com/datasets/szrlee/stock-time-series-20050101-to-20171231?select=all_stocks_2017-01-01_to_2018-01-01.csv) you mention in that #1875 resulted in unexpected NaN values for you?

Unfortunately, I was unable to replicate the issue with this dataset -- there were no unexpected NaN values in column `Date`.

I used the code below with the attached metadata. Let me know if you did something different to replicate this NaN issue. Thanks.

### Metadata & Code
**Metadata**:  [issue_1875_metadata.json](https://github.com/sdv-dev/SDV/files/14860056/issue_1875_metadata.json)


```python
import pandas as pd
from sdv.evaluation.single_table import run_diagnostic
from sdv.metadata import SingleTableMetadata
from sdv.sequential import PARSynthesizer

metadata = SingleTableMetadata.load_from_json(filepath='issue_1875_metadata.json')
data = pd.read_csv('all_stocks_2017-01-01_to_2018-01-01.csv')

synth = PARSynthesizer(metadata, epochs=1) # set epochs to 1 to save some time
synth.fit(data)
synthetic_data = synth.sample(num_sequences=31)

# this will return a score <1 if there are unexpected NaN values anywhere
diagnostic = run_diagnostic(data, synthetic_data, metadata)
print('Diagnostic score:', diagnostic.get_score())

# also explicitly check for NaN in sequence index
print('NaNs in synthetic Date column?', pd.isna(synthetic_data['Date']).any())
```

Output:
```
Diagnostic score: 1.0
NaNs in synthetic Date column? False
```

**Comment by XiaPoppy** [comment]
Hi, I mean there may exist NaN value for Open, High, Low columns in https://github.com/sdv-dev/SDV/issues/1875.

**Comment by npatki** [comment]
Hi @XiaPoppy, this issue we are chatting in is specifically for NaNs in the `sequence_index` (as specific in the metadata). The `Open` and `High` columns are not the `sequence_index` so I would suggest filing a new issue for it.

**Comment by npatki** [comment]
Hi @Ng-ms and @ImmortalSector is there any way you can share the metadata or data to help us replicate this issue? We have been unable to do so.

I'll keep this issue open because we have multiple people having the same problem. Although if our team is unable to replicate it, we may not actually be able to solve it for a while. Any and all information that may help us get to the root cause is appreciated. Thanks.

**Comment by Ng-ms** [comment]
hello @npatki  i sent you the metadata privately on slack

**Comment by ImmortalSector** [comment]
> Hi @Ng-ms and @ImmortalSector is there any way you can share the metadata or data to help us replicate this issue? We have been unable to do so.
> 
> I'll keep this issue open because we have multiple people having the same problem. Although if our team is unable to replicate it, we may not actually be able to solve it for a while. Any and all information that may help us get to the root cause is appreciated. Thanks.

I am very sorry for my late response... I am not able to replicate this issue anymore but I do remember that I had a small error about the way I was formatting my dates and since I fixed that when I was using the older version, I didn't check if it was the reason for this bug :( . Hope you can figure it out!

**Comment by npatki** [comment]
Hi @Ng-ms, indeed you had sent me the metadata already. My apologies! I was still unable to replicate the error using that metadata.

@ImmortalSector, no problem at all. Would you happen to remember what the formatting error was and how it was fixed? It will greatly help any other users coming across the issue, and potentially help identify the root cause.

**Comment by Ng-ms** [comment]
> > Hi @Ng-ms and @ImmortalSector is there any way you can share the metadata or data to help us replicate this issue? We have been unable to do so.
> > I'll keep this issue open because we have multiple people having the same problem. Although if our team is unable to replicate it, we may not actually be able to solve it for a while. Any and all information that may help us get to the root cause is appreciated. Thanks.
> 
> I am very sorry for my late response... I am not able to replicate this issue anymore but I do remember that I had a small error about the way I was formatting my dates and since I fixed that when I was using the older version, I didn't check if it was the reason for this bug :( . Hope you can figure it out!

Hi @ImmortalSector   are you still getting the same error with version 1.12 ? ..  i am still having the same error with all the versions above 1.9

**Comment by MarcJohler** [comment]
Hi together,

@npatki I think I was able to reproduce the bug with one of the Demo datasets (nasdaq100_2019). The issue seems to be, that PARSynthesizer cannot handle arbitrary variation in the length of the sequences. nadasq100_2019 has 103 sequences which almost all have the same length of 252. There are three exceptions with lengths 204, 203, and 177, which do not seem to cause any problems to the model. However, if we modify the dataset by removing a varying proportion of elements from each sequence, the model suddenly produces a lot of NaNs. Here is the code to reproduce this behavior:

```
import numpy as np
import pandas as pd
from sdv.datasets.demo import download_demo
from sdv.sequential import PARSynthesizer

# Demo for CPAR
data, metadata = download_demo(
    modality='sequential',
    dataset_name='nasdaq100_2019',
)

# Execute PAR synthesizer
synthesizer = PARSynthesizer(metadata)
synthesizer.fit(data)

synthetic_data = synthesizer.sample(num_sequences=100)
synthetic_data.isna().sum(axis = 0) # there are no NaNs for Date

# Make the sequences vary in time
modified_data = data.copy()
np.random.seed(1234)
symbols = data['Symbol'].unique()
# only select a subset of each sequence
for i, symbol in enumerate(symbols):
    # Get a boolean mask where the symbol matches
    symbol_mask = modified_data['Symbol'] == symbol
    # Select only a subset of the observations for this symbol
    modified_data = modified_data.drop(modified_data[symbol_mask].sample(frac = i / (2 * len(symbols))).index)
    
# Excecute PAR synthesizer again
synthesizer = PARSynthesizer(metadata)
synthesizer.fit(modified_data)

synthetic_modified_data = synthesizer.sample(num_sequences=100)
synthetic_modified_data.isna().sum(axis = 0) # suddenly a lot of NaNs for Date
```

There are also NaNs in other columns of both generated synthetic data sets. You might also want to investigate the reasons for that in another issue if this is not already happening.

**Comment by npatki** [comment]
Hi @MarcJohler, really appreciate you providing this example -- **we could finally replicate this issue!!** 👏 

I don't think the root cause of this issue is necessarily related to the length of each sequence, as PARSynthesizer is designed to model varied sequence lengths. Rather, it seems to be that whenever you drop the rows from a pandas DataFrame (like you did when subsetting data), the pandas DataFrame itself has a mismatched row count.

I have written more about this in #1973.

### Workaround
Until we address the issue, the workaround seems to be fairly straightforward: **If you are dropping any rows or modifying your real data in any way, be sure to reset index before fitting PAR.**

```python
modified_data_reset = modified_data.reset_index().drop(columns='index')

synthesizer = PARSynthesizer(metadata)
synthesizer.fit(modified_data_reset)
synthetic_data = synthesizer.sample(num_sequences=100)
```

For me, this got rid of any unnecessary NaN values and matched the expected behavior: A synthetic data is supposed to contain NaN values if _and only if_ the corresponding real data column also contained those NaN values. 

Hope that makes sense and let me know if you have any other thoughts. Since this issue has gotten a bit long, I suggest we use #1973 to keep track of this issue going forward.

**Comment by npatki** [comment]
Hi everyone, I'm going to mark this one as a duplicate in favor of #1973, which is specific to the root cause.

**If the workaround is not working for you** then there may be something else going wrong too. In this case, please feel free to respond here and I will reopen to continue an investigation.
