### ISSUE TITLE
Additional options for primary and foreign keys (natural keys)

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#361]
### Problem Description

Current SDV implementation only supports individual column keys of type `integer` and `string`.

We should extend this to support other options such as key values of other types (`float` and `datetime`) or composite keys (multiple columns that uniquely identify each row when put together).

This should work for both single table and multi table models, which means also adding the possibility to specify table relationships based on composite keys.

#### Metadata

`id` field subtypes should be extended to add other options. Specifying a relationship based on multiple fields, including fields of which are not of type `id` should also be possible.

#### Single Table Models

The `primary_key` argument (or corresponding metadata field) should accept a `list` of field names instead of just a `string`, and when the data is generated the combination of values of the indicated columns must be guaranteed to be unique.

#### Multi Table Models

The multi-table models should be adapted to support the relationships defined via composite keys in the Metadata.

**Comment by npatki** [comment]
This issue has been resolved with the SDV 1.0 (Beta) release.

In the [Metadata](https://docs.sdv.dev/sdv/reference/metadata-spec), the primary key is listed separately at a table level. At the column level, the type can be any natural type such as `"datetime"`, `"address"`, `"phone_number"`, etc.

**Comment by susannamau** [comment]
Hi, I installed SDV version 1.5.0, but it still does not accept composite keys.
In the metadata.json file I have:

![image](https://github.com/sdv-dev/SDV/assets/95857629/45904b96-2b93-40e3-a4a2-eacae7f18708)
but when running

`metadata = MultiTableMetadata.load_from_json(filepath='mypath')`

I get the following error message:

![image](https://github.com/sdv-dev/SDV/assets/95857629/5ee4883e-eee0-49db-871e-6a1cebe8be79)
How can I make it a tuple of strings when loading a json? I didn't find any reference to composite keys in the documentation.
Thank you
